version: "3.9"
services:
    app: 
        build: .
        container_name: zelos
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "${app_port}:3000"
        environment:
            # TODO not used in database.yml
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_HOST: gmysql
        networks:
          - mysqlnet

networks: 
  mysqlnet: 
    external: true