version: "3.9"
services:
    # db: 
    #     image: mysql:5.7
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: password
    #         MYSQL_DATABASE: app
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: password
    #     ports:
    #         - "3307:3306"
    app: 
        build: .
        container_name: zelos
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        environment:
            # TODO not used in database.yml
            DB_NAME: zelos
            DB_USER: root
            DB_PASSWORD: password
            DB_HOST: gmysql
        networks:
          - mysqlnet

networks: 
  mysqlnet: 
    external: true