# config/app.yml for rails-settings-cached
defaults: &defaults
  mail: ""
  mail: ""
  website: ""
  tax: ""
  bic: ""
  iban: ""
  address: ""
  job: ""
  name: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
